/**
 * CommaSeperatedArraySerializationLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const configuration = require("../lib/configuration");
const environments = require("../lib/Environments");

const testConfiguration = {
    ASSERT_PRECISION: 0.01,
    TEST_TIMEOUT: 30000
};

configuration.currentEnvironment = environments.TESTING;


module.exports = testConfiguration;
